### ISSUE TITLE
Inconsistent datetime representation

### ISSUE THREAD

**Issue by triceo** [zonkyio/zonky-api#1] opened 2016-09-11 14:36 UTC
The [API prescribes ISO 8601](https://github.com/zonkyio/zonky-api/blob/master/apiary.apib#L108) datetime format. (Such as `2016-09-10T11:15:33.734Z`.) 

However, the loans use a different datetime format - one which includes the time zone. (Such as `2016-09-10T10:36:59.144+02:00`.) Even then, the format seems non-standard due to the use of `:` in the offset - this makes the standard `yyyy-MM-dd'T'HH:mm:ss.SSSZ` pattern fail too.

This inconsistency requires [unnecessary workarounds](https://github.com/triceo/robozonky/blob/master/robozonky-core/src/main/java/com/github/triceo/robozonky/remote/InstantDeserializer.java) in API consumers and should, in my opinion, be fixed. Either the ISO 8601 format should be used across the board, or the colon should be dropped.

**Comment by mswiech** [comment] 2016-10-24 11:45
Hi Lukas,
I think that TZ designator '+02:00' is correct.

Our references:
[1] https://www.w3.org/TR/NOTE-datetime  

> TZD = time zone designator (Z or +hh:mm or -hh:mm)

[2] https://en.wikipedia.org/wiki/ISO_8601#Time_zone_designators

[3] http://kalendar.beda.cz/iso-8601

It looks like various TZDs are possible: 'Z' or '+0100' or '+01:00'

**Comment by petrvlcek** [comment] 2016-10-24 13:30
Hi, Triceo,

timezone offset format with colon character (`:`) should be fine and API accepts both variants - with or without it. 

Regarding failing standard pattern - this was not caused by timezone offset format but by another parsing issue that should be resolved by now.

We have changed API documentation to match input datetime format with output format to make things more clear. 

There is still one open issue regarding parsing date with time zone (i.e. `2016-08-01+02:00`), which is going to be fixed in some of upcoming releases. Before that if you want to filter by date only we recommend to use date without timezone (i.e. `2016-08-01`) where default platform timezone (`Europe/Prague`) will be applied.

**Closed as completed by petrvlcek** 2016-10-24 13:30 UTC

**Comment by triceo** [comment] 2016-10-24 14:13
@mswiech @petrvlcek Thanks, folks! I eventually figured out that I need to use `OffsetDateTime` instead of `Instant`, which magically makes the TZ designator work.
